checks:
    php: true

filter:
    excluded_paths:
        - src/AsyncTweets/CommandBundle/Tests/*
        - src/AsyncTweets/TweetBundle/Tests/*
        - src/AsyncTweets/WebsiteBundle/Tests/*
    paths:
        - src/*
