language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_install:
  - sudo apt-get install php5-sqlite

before_script:
  - composer self-update
  - composer update --prefer-dist

script: phpunit -c app/phpunit.xml.dist
