<?php

namespace AsyncTweets\TweetBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TweetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TweetRepository extends EntityRepository
{
    public function getWithUsersAndMedias()
    {
        $qb = $this->createQueryBuilder('t')
                
            ->addSelect('user')
            ->innerJoin('t.user', 'user')
            
            ->addSelect('medias')
            ->leftJoin('t.medias', 'medias')
            
            ->orderBy('t.id', 'DESC')
        ;
        
        return $qb->getQuery()->getResult();
    }
}
